{"name": "测试用例描述：错误的账号登录失败", "status": "passed", "description": "测试描述：错误的账号登录失败", "steps": [{"name": "输入错误账号", "status": "passed", "attachments": [{"name": "错误账号", "source": "5048e572-ed0b-4fe4-b4b1-9c22d7af8b6c-attachment.attach"}], "start": 1651654650598, "stop": 1651654650599}, {"name": "输入正确密码", "status": "passed", "attachments": [{"name": "正确密码", "source": "0683856c-1f00-4444-a64e-6db59de151e7-attachment.attach"}], "start": 1651654650636, "stop": 1651654650637}, {"name": "输入正确验证码", "status": "passed", "attachments": [{"name": "正确验证码", "source": "5477212e-3e8a-4dfc-8525-cf3c871dac9e-attachment.attach"}], "start": 1651654650686, "stop": 1651654650686}], "attachments": [{"name": "截图", "source": "faf7f8ad-e29d-49dc-8897-fd8ef3381098-attachment.png", "type": "image/png"}], "start": 1651654650598, "stop": 1651654653045, "uuid": "1994a8fa-b8e7-4a3e-9628-37bb103196df", "historyId": "24e424fe5694bafaaba56099b659de37", "testCaseId": "938631cc2602a20c3281e7f98df5b2bf", "fullName": "test_two.Test#test_05", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "severity", "value": "critical"}, {"name": "epic", "value": "xxx测试"}, {"name": "story", "value": "登录"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "6940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}